import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";

const Home = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const navigate = useNavigate();

  const slides = [
    {
      title: "AI-Powered Interview Prep",
      description: "Get personalized interview questions generated by AI based on your industry, role, and experience level. Practice with real-world scenarios and improve your interview skills.",
      buttonText: "Try AI Generator"
    },
    {
      title: "Skill Assessment",
      description: "Evaluate your technical and soft skills with our comprehensive assessment tools. Get detailed feedback and personalized improvement recommendations.",
      buttonText: "Assess Skills"
    },
    {
      title: "Resume Analyzer",
      description: "Get AI-powered analysis of your resume with detailed feedback on content, formatting, and keywords. Improve your chances of getting noticed by recruiters and passing ATS systems.",
      buttonText: "Analyze Resume"
    }
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentSlide((prev) => (prev < slides.length - 1 ? prev + 1 : 0));
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  const handlePrevSlide = () => {
    setCurrentSlide((prev) => (prev > 0 ? prev - 1 : slides.length - 1));
  };

  const handleNextSlide = () => {
    setCurrentSlide((prev) => (prev < slides.length - 1 ? prev + 1 : 0));
  };

  const handleButtonClick = () => {
    navigate('/login');
  };

  return (
    <div className="min-h-screen bg-gradient-to-r from-purple-50 to-pink-50">
      <div className="max-w-6xl mx-auto px-4 py-20">
        {/* AI Generator Section */}
        <div className="text-center mb-40">
          <h1 className="text-3xl md:text-4xl font-bold text-purple-600 mb-6">
            AI Job Interview Questions Generator
          </h1>
          <p className="text-lg text-gray-600 mb-8">Prepare for your job interview with AI.</p>
          
          <div className="bg-white/90 backdrop-blur-sm p-8 rounded-lg mb-10 border-l-4 border-purple-600 max-w-4xl mx-auto shadow-md">
            <p className="text-base text-gray-700 leading-relaxed">
              Our AI tool can generate the most common interview questions for your industry, job role, and level of experience. Prepare for your job interview with our AI Job Interview Questions Generator and don't let hiring managers catch you unprepared.
            </p>
          </div>
          
          <button 
            onClick={handleButtonClick}
            className="bg-gradient-to-r from-purple-600 to-pink-600 text-white py-3 px-8 rounded-lg font-semibold text-base hover:from-purple-700 hover:to-pink-700 transform hover:-translate-y-1 transition-all duration-300 shadow-md hover:shadow-lg cursor-pointer"
          >
            Generate Interview Questions
          </button>
        </div>

        {/* Feature Slider Section */}
        <div 
          className="relative h-[450px] overflow-hidden mb-20"
        >
          {slides.map((slide, index) => (
            <div
              key={index}
              className={`absolute w-full h-full p-8 transition-all duration-2000 ease-in-out transform ${
                index === currentSlide 
                  ? 'translate-x-0 opacity-100' 
                  : index < currentSlide 
                    ? '-translate-x-full opacity-0' 
                    : 'translate-x-full opacity-0'
              }`}
            >
              <div className="text-center">
                <h2 className="text-3xl md:text-4xl font-bold text-purple-600 mb-6">{slide.title}</h2>
                <p className="text-lg text-gray-700 mb-8 max-w-3xl mx-auto">{slide.description}</p>
                <button 
                  onClick={handleButtonClick}
                  className="bg-gradient-to-r from-purple-600 to-pink-600 text-white px-8 py-3 rounded-lg text-base font-semibold hover:from-purple-700 hover:to-pink-700 transition-colors duration-300 shadow-md hover:shadow-lg cursor-pointer"
                >
                  {slide.buttonText}
                </button>
              </div>
            </div>
          ))}
          
          <button
            onClick={handlePrevSlide}
            className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-600 hover:text-gray-800 transition-colors duration-300 text-5xl font-light cursor-pointer"
          >
            ‹
          </button>
          <button
            onClick={handleNextSlide}
            className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-600 hover:text-gray-800 transition-colors duration-300 text-5xl font-light cursor-pointer"
          >
            ›
          </button>
        </div>

        {/* Feature Cards Section */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-40">
          {/* AI Interview Prep Card */}
          <div className="bg-white rounded-xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 cursor-pointer" onClick={handleButtonClick}>
            <div className="w-16 h-16 bg-gradient-to-r from-purple-600 to-pink-600 rounded-full flex items-center justify-center mb-6 mx-auto">
              <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
              </svg>
            </div>
            <h3 className="text-xl font-bold text-gray-800 mb-4 text-center">AI Interview Prep</h3>
            <p className="text-base text-gray-600 text-center leading-relaxed">
              Practice with smart AI-generated questions that match your job field. Get instant feedback and tips to improve your answers, making you more confident and ready for any interview.
            </p>
          </div>

          {/* Skill Assessment Card */}
          <div className="bg-white rounded-xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 cursor-pointer" onClick={handleButtonClick}>
            <div className="w-16 h-16 bg-gradient-to-r from-purple-600 to-pink-600 rounded-full flex items-center justify-center mb-6 mx-auto">
              <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
            </div>
            <h3 className="text-xl font-bold text-gray-800 mb-4 text-center">Skill Assessment</h3>
            <p className="text-base text-gray-600 text-center leading-relaxed">
              Take easy-to-understand tests that check both your technical know-how and people skills. Get clear feedback and a simple plan to improve your weak areas and highlight your strengths.
            </p>
          </div>

          {/* Resume Analyzer Card */}
          <div className="bg-white rounded-xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 cursor-pointer" onClick={handleButtonClick}>
            <div className="w-16 h-16 bg-gradient-to-r from-purple-600 to-pink-600 rounded-full flex items-center justify-center mb-6 mx-auto">
              <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
              </svg>
            </div>
            <h3 className="text-xl font-bold text-gray-800 mb-4 text-center">Resume Analyzer</h3>
            <p className="text-base text-gray-600 text-center leading-relaxed">
              Let our AI check your resume and make it better. It helps you use the right words, fix formatting, and make sure hiring managers and computer systems can easily find your best qualities.
            </p>
          </div>
        </div>

        {/* Footer Section */}
        <footer className="border-t border-gray-200 pt-12 pb-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
            <div>
              <h4 className="text-lg font-bold text-gray-800 mb-4">SkillMatrix</h4>
              <p className="text-sm text-gray-600 leading-relaxed">Empowering professionals with AI-driven tools for career success.</p>
            </div>
            <div>
              <h4 className="text-base font-semibold text-gray-800 mb-4">Features</h4>
              <ul className="space-y-3">
                <li><a href="#" className="text-sm text-gray-600 hover:text-purple-600 transition-colors cursor-pointer" onClick={handleButtonClick}>AI Interview Prep</a></li>
                <li><a href="#" className="text-sm text-gray-600 hover:text-purple-600 transition-colors cursor-pointer" onClick={handleButtonClick}>Skill Assessment</a></li>
                <li><a href="#" className="text-sm text-gray-600 hover:text-purple-600 transition-colors cursor-pointer" onClick={handleButtonClick}>Resume Analyzer</a></li>
              </ul>
            </div>
            <div>
              <h4 className="text-base font-semibold text-gray-800 mb-4">Company</h4>
              <ul className="space-y-3">
                <li><a href="#" className="text-sm text-gray-600 hover:text-purple-600 transition-colors cursor-pointer" onClick={handleButtonClick}>About Us</a></li>
                <li><a href="#" className="text-sm text-gray-600 hover:text-purple-600 transition-colors cursor-pointer" onClick={handleButtonClick}>Careers</a></li>
                <li><a href="#" className="text-sm text-gray-600 hover:text-purple-600 transition-colors cursor-pointer" onClick={handleButtonClick}>Contact</a></li>
              </ul>
            </div>
            <div>
              <h4 className="text-base font-semibold text-gray-800 mb-4">Legal</h4>
              <ul className="space-y-3">
                <li><a href="#" className="text-sm text-gray-600 hover:text-purple-600 transition-colors cursor-pointer" onClick={handleButtonClick}>Privacy Policy</a></li>
                <li><a href="#" className="text-sm text-gray-600 hover:text-purple-600 transition-colors cursor-pointer" onClick={handleButtonClick}>Terms of Service</a></li>
                <li><a href="#" className="text-sm text-gray-600 hover:text-purple-600 transition-colors cursor-pointer" onClick={handleButtonClick}>Cookie Policy</a></li>
              </ul>
            </div>
          </div>
          <div className="text-center text-gray-600">
            <p className="text-sm">&copy; {new Date().getFullYear()} SkillMatrix. All rights reserved.</p>
          </div>
        </footer>
      </div>
    </div>
  );
};

export default Home;